import os
import json
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

def main():
    # Create models directory if it doesn't exist
    os.makedirs("models", exist_ok=True)
    os.makedirs("results", exist_ok=True)

    # 1. Load Preprocessed Data
    print("Loading preprocessed data...")
    
    # We load padded sequences and labels generated by Member 1
    padded_path = "data/processed/padded.npy"
    labels_path = "data/processed/labels.csv"
    
    if os.path.exists(padded_path) and os.path.exists(labels_path):
        X = np.load(padded_path)
        y = pd.read_csv(labels_path)["label_num"].values
    else:
        # Fallback if they are in different locations or named differently
        # Attempt to read data/processed.csv if present
        fallback_csv = "data/processed.csv"
        if not os.path.exists(fallback_csv):
            fallback_csv = "data/processed/cleaned.csv"
            
        print(f"Loading fallback from {fallback_csv}...")
        df = pd.read_csv(fallback_csv)
        if "label_num" not in df.columns:
            df["label_num"] = df["label"].map({"ham": 0, "spam": 1})
        
        # Tokenize on the fly
        from tensorflow.keras.preprocessing.text import Tokenizer
        from tensorflow.keras.preprocessing.sequence import pad_sequences
        
        tokenizer = Tokenizer(num_words=5000, oov_token="<OOV>")
        # Fill NaN values in clean_message if any
        messages = df["clean_message"].fillna("").astype(str).tolist()
        tokenizer.fit_on_texts(messages)
        sequences = tokenizer.texts_to_sequences(messages)
        X = pad_sequences(sequences, maxlen=100, padding="post", truncating="post")
        y = df["label_num"].values

    print(f"Dataset shape: {X.shape}, Labels shape: {y.shape}")

    # 2. Train-Test Split (80% training, 20% validation/testing)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    print(f"Train set: {X_train.shape}, Test set: {X_test.shape}")

    # Model Parameters
    vocab_size = 5000
    embedding_dim = 64
    max_len = 100

    # 3. Build Model Architecture
    print("\nBuilding LSTM Model...")
    model = Sequential([
        Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len, mask_zero=True),
        LSTM(64, return_sequences=False),
        Dropout(0.2), # Dropout layer to avoid overfitting
        Dense(1, activation='sigmoid')
    ])

    # 4. Compile Model
    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )
    
    model.summary()

    # 5. Train Model
    print("\nTraining LSTM Model...")
    history = model.fit(
        X_train, y_train,
        epochs=10,
        batch_size=64,
        validation_data=(X_test, y_test)
    )

    # 6. Evaluate Model
    print("\nEvaluating Model on Test Set...")
    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
    print(f"Test Loss: {loss:.4f}")
    print(f"Test Accuracy: {accuracy:.4f}")

    # Predict classes
    y_pred_probs = model.predict(X_test)
    y_pred = (y_pred_probs > 0.5).astype(int).flatten()

    # Classification metrics
    print("\nClassification Report:")
    report = classification_report(y_test, y_pred, target_names=["Ham", "Spam"])
    print(report)

    # Confusion Matrix
    print("Confusion Matrix:")
    cm = confusion_matrix(y_test, y_pred)
    print(cm)

    # 7. Save Trained Model
    print("\nSaving trained model to models/spam_model.h5...")
    model.save("models/spam_model.h5")
    
    # Save training history and evaluation metrics for Member 3
    history_dict = history.history
    history_dict["test_loss"] = float(loss)
    history_dict["test_accuracy"] = float(accuracy)
    
    with open("results/lstm_history.json", "w") as f:
        json.dump(history_dict, f)
        
    print("Model and history successfully saved!")

if __name__ == "__main__":
    main()
